- name: checking data types
  hosts: localhost
  vars:
    NAME: Siva
    Skills: 
    - Devops
    - Shell
    - Ansible
    - Linux
    - SQL
    Experience:
      Devops: 4
      AWS: 2
      SQL: 4
    TRAINER: True
  tasks:
   - name: print key value pair
     ansible.builtin.debug:
      msg: "name: {{NAME}}"
  
   - name: print list
      ansible.builtin.debug:
        msg: "skills: {{skills}}"
   - name: print map
    ansible.builtin.debug:
      mag: "Experience: {{Experience}}"
 
  - name: print boolean
    ansible.builtin.debug:
      msg: "TRAINER: {{TRAINER}}"
