- name: loops # install and uninstall packages
  hosts: localhost
  become: yes
  tsaks:
  - name: install and uninstall packages
    ansible.builtin.packages:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
      - {name: 'git', state: 'present'}
      - {name: 'mysql', state: 'absent'}
      - {name: 'postfix', state: 'absent'}
      - {name: 'nginx', state: 'present'}

      